TravelApp.Web/Controllers/BlogController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelApp.Contracts.DTO;
using TravelApp.Contracts.Interface;

namespace TravelApp.Web.Controllers
{
    public class BlogController : Controller
    {
        ICommentService _commentService;
        IBlogService _blogService;
        public BlogController(IBlogService blogService, ICommentService commentService)
        {
            _blogService = blogService;
            _commentService = commentService;
        }
        // GET: Blog
        public ActionResult Index()
        {
            return View();
        }

        // GET: Blog/Details/5
        [Authorize(Roles = "User,Admin")]
        public ActionResult Details(int id)
        {
            ViewBag.ID = id;
            return View();
        }

        // GET: Blog/Create
        [Authorize(Roles = "User,Admin")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: Blog/Create
        [HttpPost]
        [ValidateInput(false)]
        [Authorize(Roles = "User,Admin")]
        public ActionResult Create(BlogDto blogDto, HttpPostedFileBase fileUpload)
        {
            try
            {
                var fileName = Path.GetFileName(fileUpload.FileName);
                // store the file inside ~/App_Data/uploads folder
                var path = Path.Combine(Server.MapPath("~/Uploads"), fileName);
                fileUpload.SaveAs(path);
                blogDto.BlogCoverPhoto += fileName;

                blogDto.User = new UserDto() { Id = User.Identity.GetUserId() };
                _blogService.CreateBlog(blogDto);

                return RedirectToAction("Index");
            }
            catch (DbEntityValidationException e)
            {
                foreach (var eve in e.EntityValidationErrors)
                {
                    Console.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                        eve.Entry.Entity.GetType().Name, eve.Entry.State);
                    foreach (var ve in eve.ValidationErrors)
                    {
                        Console.WriteLine("- Property: \"{0}\", Error: \"{1}\"",
                            ve.PropertyName, ve.ErrorMessage);
                    }
                }
                throw;
            }
            catch (NullReferenceException ex)
            {

                throw;
            }
        }

        // GET: Blog/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Blog/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Blog/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Blog/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public ActionResult GetAllBlogs()
        {
            var jsonResult = Json(_blogService.GetBlogs(), JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;
        }

        [HttpGet]
        public ActionResult GetSingleBlog(int id)
        {
            var jsonResult = Json(_blogService.GetBlog(id), JsonRequestBehavior.AllowGet);
            jsonResult.MaxJsonLength = int.MaxValue;
            return jsonResult;
        }

        [HttpPost]
        public ActionResult CreateComment(CommentDto comment)
        {
            try
            {
                comment.UserDto = new UserDto()
                {
                    Id = User.Identity.GetUserId()
                };
                _commentService.CreateBlogComment(comment);
                return Json("Ok", JsonRequestBehavior.AllowGet);
            }
            catch (DbEntityValidationException e)
            {
                foreach (var eve in e.EntityValidationErrors)
                {
                    Console.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                        eve.Entry.Entity.GetType().Name, eve.Entry.State);
                    foreach (var ve in eve.ValidationErrors)
                    {
                        Console.WriteLine("- Property: \"{0}\", Error: \"{1}\"",
                            ve.PropertyName, ve.ErrorMessage);
                    }
                }
                throw;
            }

        }
    }
}

TravelApp.Web/Controllers/FavouriteController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelApp.Contracts.DTO;
using TravelApp.Contracts.Interface;

namespace TravelApp.Web.Controllers
{
    public class FavouriteController : Controller
    {
        IFavouriteService _favouriteService;
        public FavouriteController(IFavouriteService favouriteService)
        {
            _favouriteService = favouriteService;
        }

        // GET: Favourite
        [Authorize(Roles = "Admin,User")]
        public ActionResult Index()
        {
            return View();
        }

        // GET: Favourite/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Favourite/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Favourite/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Favourite/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Favourite/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Favourite/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Favourite/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //api calls
        [HttpGet]
        public ActionResult GetAttractionsByUserId()
        {
            try
            {
                var attractions = _favouriteService.GetAllByUserId(User.Identity.GetUserId());
                foreach (AttractionDto attraction in attractions)
                {
                    if (!string.IsNullOrWhiteSpace(attraction.Photos))
                    {
                        attraction.Photos = attraction.Photos.Split(',')[0];
                    }
                }
                return Json(attractions, JsonRequestBehavior.AllowGet);
            }
            catch(Exception ex)
            {
                throw;
            }
        }
    }
}

TravelApp.Web/Controllers/TripPlanController.cs
using Microsoft.AspNet.Identity;
using NReco.PdfGenerator;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Runtime.Serialization.Json;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using TravelApp.Contracts.DTO;
using TravelApp.Contracts.Interface;

namespace TravelApp.Web.Controllers
{
    public class TripPlanController : Controller
    {

        ITripPlanService _tripPlanService;
        ICountryService _countryService;
        IAttractionService _attractionService;
        public TripPlanController(ICountryService countryService, IAttractionService attractionSevice, ITripPlanService tripPlanService)
        {
            _countryService = countryService;
            _attractionService = attractionSevice;
            _tripPlanService = tripPlanService;
        }
        // GET: TripPlan
        [Authorize(Roles = "User,Admin")]
        public ActionResult Index()
        {
            return View();
        }

        // GET: TripPlan/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(AngularPostObject tripPlanObject)
        {
            TripPlanDto tripPlan = new TripPlanDto()
            {
                Directions = tripPlanObject.Directions,
                HoursPerDay = tripPlanObject.HoursPerDay,
                Transport = tripPlanObject.Transport,
                CreateDate = DateTime.Now,
                GuidId = Guid.NewGuid(),
                User = new UserDto() { Id = User.Identity.GetUserId() }
            };
            foreach (int item in tripPlanObject.Attractions)
            {
                tripPlan.PdfFile += item + ",";
            }

            _tripPlanService.Create(tripPlan);

            string id = _tripPlanService.GetByGuid(tripPlan.GuidId).GuidId.ToString();

            return Json(_tripPlanService.GetByGuid(tripPlan.GuidId).GuidId, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult DownloadTripPlan(string id)
        {
            TripPlanDto tripPlan = _tripPlanService.GetByGuid(Guid.Parse(id));

            string[] attractionId = tripPlan.PdfFile.Split(',');

            List<AttractionDto> attractionList = new List<AttractionDto>();
            for (int i = 0; i < attractionId.Length - 1; i++)
            {
                attractionList.Add(_attractionService.GetAttraction(int.Parse(attractionId[i])));
            }

            foreach (var item in attractionList)
            {
               item.Adress= item.Adress.Replace(' ', '+');
            }

            // var MapUrl = "https://maps.googleapis.com/maps/api/staticmap?center=Brooklyn+Bridge,New+York&markers=,
            //NY &markers=color:blue%7Clabel:S%7CBrooklyn+Bridge,New+York,NY&markers=color:green%7Clabel:G%7C40.711614,-74.012318&
            //markers=color:red%7Clabel:C%7C40.718217,-73.998284&key=AIzaSyD6bvtJUx9M1MP0FQ-eY26w_uMSxWgZhy0";

            string adressString = "https://maps.googleapis.com/maps/api/staticmap?zoom=13&size=1000x500&maptype=roadmap&center=" + attractionList[0].Adress;
            foreach (var item in attractionList)
            {
                adressString += "&markers=color:blue%7Clabel:S%7C" + item.Adress;
            }
            adressString += "&key=AIzaSyD6bvtJUx9M1MP0FQ-eY26w_uMSxWgZhy0";
            foreach (var item in attractionList)
            {
                item.Adress = item.Adress.Replace('+', ' ');
                item.Photos = "C:/Users/fum19_000/Source/Repos/TravelApp/TravelApp/TravelApp.Web/Uploads/" + item.Photos.Split(',')[0];
            }
            


           PdfTemplateDto listToPdfTemplate = new PdfTemplateDto()
            {
                Attractions=attractionList,
                DirectionForCity=tripPlan.Directions,
                HoursPerDay=tripPlan.HoursPerDay,
                MapUrl=adressString
            };
            listToPdfTemplate.DirectionForCity = listToPdfTemplate.DirectionForCity.Replace("Total Distance" ,"Całkowity dystans");
            WebRequest request = WebRequest.Create("http://fum1993-001-site1.btempurl.com/TripPlan/Template");
            request.Method = "POST";
            request.ContentType = "application/json; charset=utf-8";
            DataContractJsonSerializer ser = new DataContractJsonSerializer(listToPdfTemplate.GetType());
            StreamWriter writer = new StreamWriter(request.GetRequestStream());
            JavaScriptSerializer jss = new JavaScriptSerializer();

            string yourdata = jss.Serialize(listToPdfTemplate);
            writer.Write(yourdata);
            writer.Close();

            WebResponse response = request.GetResponse();
            Stream data = response.GetResponseStream();
            string html = String.Empty;
            using (StreamReader sr = new StreamReader(data))
            {
                html = sr.ReadToEnd();
            }
            var htmlToPdf = new NReco.PdfGenerator.HtmlToPdfConverter();
            var pdfBytes = htmlToPdf.GeneratePdf(html);
            Response.Clear();
            Response.ContentType = "application/pdf; charset=utf-8";
            Response.BinaryWrite(pdfBytes);
            string fileName = string.Format("TwojPlanWycieczki_.pdf");
            Response.AddHeader("Content-Disposition",
               string.Format("attachment; filename={0}", fileName));
            Response.End();

            return Json(pdfBytes, JsonRequestBehavior.AllowGet);
        }

        // GET: TripPlan/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: TripPlan/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: TripPlan/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }


        public ActionResult Template(PdfTemplateDto listPdfTemplate)
        {
            return View(listPdfTemplate);
        }

        //public ActionResult GetPdf()
        //{

        //    var pdfBytes = Convert.FromBase64String(Base64Decode(_tripPlanService.GetTripPlanById(4).PdfFile));

        //    ;
        //    Response.ContentType = "application/pdf";
        //    Response.ContentEncoding = System.Text.Encoding.UTF8;
        //    Response.AddHeader("Content-Disposition", "Inline; filename=TEST.pdf");
        //    Response.BinaryWrite(pdfBytes);
        //    Response.Flush();
        //    Response.End();
        //    return RedirectToAction("Index");
        //}
        // POST: TripPlan/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public ActionResult GetAllCountries()
        {

            return Json(_countryService.GetCountries(), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetAttractionByCityId(int id)
        {

            return Json(_attractionService.GetAttractionByCityId(id), JsonRequestBehavior.AllowGet);
        }

        public static string Base64Encode(string plainText)
        {
            var plainTextBytes = System.Text.Encoding.UTF8.GetBytes(plainText);
            return System.Convert.ToBase64String(plainTextBytes);
        }



        public static string Base64Decode(string base64EncodedData)
        {
            var base64EncodedBytes = System.Convert.FromBase64String(base64EncodedData);
            return System.Text.Encoding.UTF8.GetString(base64EncodedBytes);
        }
    }
}

TravelApp.Web/Views/Shared/_AttractionPartial.cshtml
@model TravelApp.Contracts.DTO.AttractionDto

<div class="row">
    <h4>@Html.DisplayFor(model => model.Name)</h4>
    <hr />
    <div class="col-sm-12">
        <img src=@Model.Photos alt="Nie udało sie zaladować obrazka" style="max-height:600px;max-width:600px;"  />
    </div>

    <div class="col-sm-2">
       <h6>Opis atrakcji:</h6>
    </div>


    <div class="col-sm-10">
        @Html.DisplayFor(model => model.LongDescription)
    </div>


    <div class="col-sm-12">
        <h4>Adres atrakcji: @Html.DisplayFor(model => model.Adress) </h4>
    </div>

    <div class="col-sm-12">
        <h4> Średni czas zwiedzania: @Html.DisplayFor(model => model.AvrHoursTime)</h4>
</div>

</div>

TravelApp.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html ng-app="myApp">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Plan A Trip</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <style>
        .navbar-default, #footerwrap {
            background-color: cadetblue;
        }

            #footerwrap p {
                color: white;
            }
    </style>
</head>
<body>
    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#sufix">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("TravelApp", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div id="sufix" class="navbar-collapse collapse navbar-right">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Zaplanuj przygode", "Index", "TripPlan")</li>
                    <li>@Html.ActionLink("Atrakcje", "Index", "Attraction")</li>
                    <li>@Html.ActionLink("Artykuły", "Index", "Blog")</li>
                    <li>@Html.ActionLink("Ulubione", "Index", "Favourite")</li>
                    @*<li>@Html.ActionLink("About", "About", "Home")</li>*@
                    @*<li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@
                </ul>
                @Html.Partial("_LoginPartial")
            </div><!--/.nav-collapse -->
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()

        <!-- *****************************************************************************************************************
        TESTIMONIALS
        ***************************************************************************************************************** -->

        <hr />
        <!-- *****************************************************************************************************************
         FOOTER
         ***************************************************************************************************************** -->
        <div id="footerwrap" style="padding-top:10px;padding-bottom:5px; color:white;">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="hline-w"></div>
                        <p style="padding-top:0px;padding-bottom:0px;">
                            Strona została wykonana przez Michała Szuma i korzysta z darmowego szablonu bootstrap o nazwie Solid
                            <a href="#"><i class="fa fa-dribbble"></i></a>
                            <a href="#"><i class="fa fa-facebook"></i></a>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                            <a href="#"><i class="fa fa-tumblr"></i></a>
                        </p>
                    </div>
                </div><! --/row -->
            </div><! --/container -->
        </div><! --/footerwrap -->
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/angular")

    @*<script>
            (function ($) {
                "use strict";
                var $container = $('.portfolio'),
                    $items = $container.find('.portfolio-item'),
                    portfolioLayout = 'fitRows';

                if ($container.hasClass('portfolio-centered')) {
                    portfolioLayout = 'masonry';
                }

                $container.isotope({
                    filter: '*',
                    animationEngine: 'best-available',
                    layoutMode: portfolioLayout,
                    animationOptions: {
                        duration: 750,
                        easing: 'linear',
                        queue: false
                    },
                    masonry: {
                    }
                }, refreshWaypoints());

                function refreshWaypoints() {
                    setTimeout(function () {
                    }, 1000);
                }

                $('nav.portfolio-filter ul a').on('click', function () {
                    var selector = $(this).attr('data-filter');
                    $container.isotope({ filter: selector }, refreshWaypoints());
                    $('nav.portfolio-filter ul a').removeClass('active');
                    $(this).addClass('active');
                    return false;
                });

                function getColumnNumber() {
                    var winWidth = $(window).width(),
                    columnNumber = 1;

                    if (winWidth > 1200) {
                        columnNumber = 5;
                    } else if (winWidth > 950) {
                        columnNumber = 4;
                    } else if (winWidth > 600) {
                        columnNumber = 3;
                    } else if (winWidth > 400) {
                        columnNumber = 2;
                    } else if (winWidth > 250) {
                        columnNumber = 1;
                    }
                    return columnNumber;
                }

                function setColumns() {
                    var winWidth = $(window).width(),
                    columnNumber = getColumnNumber(),
                    itemWidth = Math.floor(winWidth / columnNumber);

                    $container.find('.portfolio-item').each(function () {
                        $(this).css({
                            width: itemWidth + 'px'
                        });
                    });
                }

                function setPortfolio() {
                    setColumns();
                    $container.isotope('reLayout');
                }

                $container.imagesLoaded(function () {
                    setPortfolio();
                });

                $(window).on('resize', function () {
                    setPortfolio();
                });
            })(jQuery);
        </script>*@

    @RenderSection("scripts", required: false)

</body>
</html>