TravelApp.Web/Areas/Admin/Controllers/AttractionController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelApp.Contracts.DTO;
using TravelApp.Contracts.Interface;

namespace TravelApp.Web.Areas.Admin.Controllers
{
    public class AttractionController : Controller
    {
        IAttractionService _attractionService;
        ICountryService _countryService;
        public AttractionController(IAttractionService attractionSevice,ICountryService countryService)
        {
            _attractionService = attractionSevice;
            _countryService = countryService;
        }
        [HttpGet]
        public ActionResult GetAllAttraction()
        {
            return Json(_attractionService.GetAttractions(), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult SetVisibleAttraction(int id)
        {
            _attractionService.SetAttractionVisible(id);
            return RedirectToAction("Index");
        }

        // GET: Admin/Attraction
        [Authorize(Roles = "Admin")]
        public ActionResult Index()
        {
            return View(_attractionService.GetAdminAttractions());
        }

        // GET: Admin/Attraction/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Admin/Attraction/Create
        public ActionResult Create()
        {
            var list = _countryService.GetCountries().OrderBy(r => r.Name).ToList().Select(rr =>
                 new SelectListItem { Value = rr.Id.ToString(), Text = rr.Name }).ToList();
            ViewBag.countryName = list;
            var listCity = new List<SelectListItem>() { 
                  new SelectListItem { Value = "Select", Text = "Select" }};          
            ViewBag.cityName = listCity;
            return View();
        }

        // POST: Admin/Attraction/Create
        [HttpPost]
        public ActionResult Create(AttractionDto attractionDto,int countryName,int cityName, List<HttpPostedFileBase> fileUpload)
        {

            try
            {
                foreach (HttpPostedFileBase item in fileUpload)
                {
                    var fileName = Path.GetFileName(item.FileName);
                    // store the file inside ~/App_Data/uploads folder
                    var path = Path.Combine(Server.MapPath("~/Uploads"), fileName);
                    item.SaveAs(path);
                    attractionDto.Photos += fileName + ",";
                }

                var list = _countryService.GetCountries().OrderBy(r => r.Name).ToList().Select(rr =>
                 new SelectListItem { Value = rr.Id.ToString(), Text = rr.Name }).ToList();
                ViewBag.countryName = list;
                list.Clear();
                var listCity = new List<SelectListItem>() {
                  new SelectListItem { Value = "Select", Text = "Select" }};
                ViewBag.cityName = listCity;
                attractionDto.City = new CityDto()
                {
                    Id = cityName
                };
                attractionDto.Country = new CountryDto()
                {
                    Id = countryName
                };
                _attractionService.CreateAttraction(attractionDto);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Admin/Attraction/Edit/5
        public ActionResult Edit(int id)
        {
            AttractionDto attraction = _attractionService.GetAttraction(id);
            var list = _countryService.GetCountries().OrderBy(r => r.Name).ToList().Select(rr =>
                 new SelectListItem { Value = rr.Id.ToString(), Text = rr.Name }).ToList();
            ViewBag.countryName = list;
            var listCity = new List<SelectListItem>() {
                  new SelectListItem { Value = "Select", Text = "Select" }};
            ViewBag.cityName = listCity;
            
            return View(attraction);
        }

        // POST: Admin/Attraction/Edit/5
        [HttpPost]
        public ActionResult Edit(AttractionDto attractionDto, int countryName, int cityName)
        {
            try
            {

                var list = _countryService.GetCountries().OrderBy(r => r.Name).ToList().Select(rr =>
                 new SelectListItem { Value = rr.Id.ToString(), Text = rr.Name }).ToList();
                ViewBag.countryName = list;
                var listCity = new List<SelectListItem>() {
                  new SelectListItem { Value = "Select", Text = "Select" }};
                ViewBag.cityName = listCity;
                attractionDto.City = new CityDto()
                {
                    Id = cityName
                };
                attractionDto.Country = new CountryDto()
                {
                    Id = countryName
                };
                _attractionService.EditAttraction(attractionDto);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            try
            {
                // TODO: Add delete logic here
                _attractionService.DeleteAttraction(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
        [HttpGet]
        public ActionResult GetCitiesByCountryId(int id)
        {
            IEnumerable<CityDto> city = _countryService.GetCitiesByCountryId(id);
            return Json(city, JsonRequestBehavior.AllowGet);
        }
    }
}

TravelApp.Web/Controllers/AttractionController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity.Validation;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TravelApp.Contracts.DTO;
using TravelApp.Contracts.Interface;

namespace TravelApp.Web.Controllers
{
    public class AttractionController : Controller
    {
        IAttractionService _attractionService;
        ICountryService _countryService;
        ICommentService _commentService;
        IRankService _rankService;
        IFavouriteService _favouriteService;
        public AttractionController(IAttractionService attractionService, ICountryService countryService, ICommentService commentService, IRankService rankService, IFavouriteService favouriteService)
        {
            _attractionService = attractionService;
            _countryService = countryService;
            _commentService = commentService;
            _rankService = rankService;
            _favouriteService = favouriteService;

        }

        // GET: Attraction
        public ActionResult Index()
        {
            return View();
        }

        // GET: Attraction/Details/5
        [Authorize(Roles = "User,Admin")]
        public ActionResult Details(int id)
        {
            ViewBag.ID = id;
            return View(_attractionService.GetAttraction(id));
        }

        // GET: Admin/Attraction/Create
        [Authorize(Roles = "Admin,User")]
        public ActionResult Create()
        {
            var list = _countryService.GetCountries().OrderBy(r => r.Name).ToList().Select(rr =>
                 new SelectListItem { Value = rr.Id.ToString(), Text = rr.Name }).ToList();
            ViewBag.countryName = list;
            var listCity = new List<SelectListItem>() {
                  new SelectListItem { Value = "Select", Text = "Select" }};
            ViewBag.cityName = listCity;
            return View();
        }

        // POST: Admin/Attraction/Create
        [HttpPost]
        [Authorize(Roles = "User,Admin")]
        public ActionResult Create(AttractionDto attractionDto, int countryName, int cityName, List<HttpPostedFileBase> fileUpload)
        {

            try
            {
                foreach (HttpPostedFileBase item in fileUpload)
                {
                    var fileName = Path.GetFileName(item.FileName);
                    // store the file inside ~/App_Data/uploads folder
                    var path = Path.Combine(Server.MapPath("~/Uploads"), fileName);
                    item.SaveAs(path);
                    attractionDto.Photos += fileName + ",";
                }

                var list = _countryService.GetCountries().OrderBy(r => r.Name).ToList().Select(rr =>
                  new SelectListItem { Value = rr.Id.ToString(), Text = rr.Name }).ToList();
                ViewBag.countryName = list;
                list.Clear();
                var listCity = new List<SelectListItem>() {
                  new SelectListItem { Value = "Select", Text = "Select" }};
                ViewBag.cityName = listCity;
                attractionDto.City = new CityDto()
                {
                    Id = cityName
                };
                attractionDto.Country = new CountryDto()
                {
                    Id = countryName
                };
                _attractionService.CreateAttraction(attractionDto);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Attraction/Edit/5
        public ActionResult Edit()
        {
            return View();
        }

        // POST: Attraction/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        //api calls
        [HttpGet]
        public ActionResult GetCitiesByCountryId(int id)
        {
            IEnumerable<CityDto> city = _countryService.GetCitiesByCountryId(id);
            return Json(city, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public ActionResult GetAllAttractions()
        {
            IEnumerable<AttractionDto> attractions = _attractionService.GetAttractions();

            foreach (AttractionDto attraction in attractions)
            {
                if (!string.IsNullOrWhiteSpace(attraction.Photos))
                {
                    attraction.Photos = attraction.Photos.Split(',')[0];
                }
            }
            return Json(attractions, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult GetSingleAttraction(int id)
        {
            AttractionDto attraction = _attractionService.GetAttraction(id);
            attraction.PhotosArray = attraction.PhotosArray.Where(x => x != "").ToArray();
            for (int i = 0; i < attraction.PhotosArray.Length; i++)
            {
                attraction.PhotosArray[i] = "/Uploads/" + attraction.PhotosArray[i];
            }
            return Json(attraction, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]

        public ActionResult CreateComment(CommentDto comment)
        {
            try
            {
                comment.UserDto = new UserDto()
                {
                    Id = User.Identity.GetUserId()
                };
                _commentService.CreateAttractionComment(comment);
                return Json("Ok", JsonRequestBehavior.AllowGet);
            }
            catch (DbEntityValidationException e)
            {
                foreach (var eve in e.EntityValidationErrors)
                {
                    Console.WriteLine("Entity of type \"{0}\" in state \"{1}\" has the following validation errors:",
                        eve.Entry.Entity.GetType().Name, eve.Entry.State);
                    foreach (var ve in eve.ValidationErrors)
                    {
                        Console.WriteLine("- Property: \"{0}\", Error: \"{1}\"",
                            ve.PropertyName, ve.ErrorMessage);
                    }
                }
                throw;
            }
        }

        [HttpGet]
        [Authorize(Roles = "Admin,User")]
        public bool CheckIfIsFavourite(int id)
        {
            try
            {
                if (string.IsNullOrWhiteSpace(User.Identity.GetUserId()))
                {
                    return false;
                }
                else
                {
                    return _favouriteService.CheckIfIsFavourite(id, User.Identity.GetUserId());
                }
            }
            catch (Exception ex)
            {
                throw;
            }
        }
        [HttpGet]
        public bool CreateFavourite(int id)
        {
            try
            {
                _favouriteService.CreateFavourite(new FavouriteDto()
                {
                    Attraction = new AttractionDto() { Id = id },
                    UserDto = new UserDto() { Id = User.Identity.GetUserId() }
                });
                return true;
            }
            catch (Exception ex)
            {
                return false;
            }
        }

        [HttpGet]
        public bool RemoveFavourite(int id)
        {
            try
            {
                _favouriteService.DeleteFavourite(new FavouriteDto()
                {
                    Attraction = new AttractionDto() { Id = id },
                    UserDto = new UserDto() { Id = User.Identity.GetUserId() }
                });
                return true;
            }
            catch (Exception ex)
            {
                return false;
            }
        }

        [HttpPost]
        public bool CreateRank(RankDto rank)
        {
            try
            {
                rank.User = new UserDto()
                {
                    Id = User.Identity.GetUserId()
                };
                _rankService.CreateRank(rank);
                return true;
            }
            catch (Exception ex)
            {
                return false;
            }
        }

        [HttpPost]
        public bool ChangeRank(RankDto rank)
        {
            try
            {
                rank.User = new UserDto()
                {
                    Id = User.Identity.GetUserId()
                };
                _rankService.EditRank(rank);
                return true;
            }
            catch (Exception ex)
            {
                return false;
            }
        }

        [HttpGet]
        public bool CheckIfIsRanked(int id)
        {
            try
            {
                return _rankService.CheckIfHaveRank(id, User.Identity.GetUserId());
            }
            catch (Exception ex)
            {
                throw;
            }
        }

        [HttpGet]
        public ActionResult GetAttractionRank(int id)
        {
            try
            {
                return Json(_rankService.GetRankWithAttractionIdAndUserId(id, User.Identity.GetUserId()), JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                throw;
            }
        }

    }
}

TravelApp.Web/Areas/Admin/Views/Attraction/Create.cshtml
@model TravelApp.Contracts.DTO.AttractionDto

@{
    ViewBag.Title = "Nowa atrakcja";
}

<h2>Nowa atrakcja</h2>
@using (Html.BeginForm("Create", "Attraction", FormMethod.Post, new { enctype = "multipart/form-data", id = "frmID" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <div>
        Nazwa atrakcji
    </div>
    <p>
        @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
    </p>
    <p>
        Krótki Opis
    </p>
    <p>

        @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
    </p>
    <p>
        Długi Opis
    </p>
    <p>

        @Html.TextAreaFor(model => model.LongDescription, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.LongDescription, "", new { @class = "text-danger" })
    </p>
    <p>
        Adres
    </p>
    <p>

        @Html.TextBoxFor(model => model.Adress, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Adress, "", new { @class = "text-danger" })
    </p>
    <p>
        Średni czas zwiedzania
    </p>
    <p>

        @Html.TextBoxFor(model => model.AvrHoursTime, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.AvrHoursTime, "", new { @class = "text-danger" })
    </p>
    <p>
        Zdjęcie
    </p>
    <p>
        @Html.HiddenFor(i => i.FilesToBeUploaded)
        <div class="labelstyle">
            <label>Pliki</label>
        </div>

        <div id="uploaders">
            <input type="file" id="fileToUpload" name="fileUpload" multiple="multiple" style="float: left;" />
            <br />
            <span id="spnFile" style="float: left; color: #FF0000"></span>
            @Html.ValidationMessage("File")
            @Html.Hidden("hdnFileUpload")
        </div>
        <br />
        <div class="col-lg-6">
        </div>
        <br />
        <div class="control-section" style="padding: 0px;">
            <div id="selectedFiles"></div>
        </div>
    </p>
    <p>
        Kraj
    </p>
    <p>
        @Html.DropDownList("countryName", null, "Wybierz", new { @id = "Country", @class = "form-control" })
    </p>
    <p>
        Miasto
    </p>
    <p>

        @Html.DropDownList("cityName", null, "Wybierz", new { @id = "City", @class = "form-control" })
    </p>
        <p>
        </p>
        <input type="submit" value="Zapisz" onclick="createAttraction.Check" class="form-control" />
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script type="text/javascript">
    var createAttraction = {
        init: function () {
            var citiesSelect = $('#City');
            citiesSelect.empty();
            citiesSelect.append($('<option/>', {
                value: "0",
                text: "Wybierz"
            }));
        }
    }
    $(document).ready(function () {
        createAttraction.init();
        $('#Country').change(function () {
            var selectedCountry = $(this).val();

            if (selectedCountry != null && selectedCountry != '') {
                $.getJSON('@Url.Action("GetCitiesByCountryId")', { id: selectedCountry }, function (cities) {
                    var citiesSelect = $('#City');
                    citiesSelect.empty();
                    citiesSelect.append($('<option/>', {
                        value: "0",
                        text: "Wybierz"
                    }));
                    $.each(cities, function (index, city) {
                        citiesSelect.append($('<option/>', {
                            value: city.Id,
                            text: city.Name
                        }));
                    });
                });
            }
            else {
                var citiesSelect = $('#City');
                citiesSelect.empty();
                citiesSelect.append($('<option/>', {
                    value: "0",
                    text: "Wybierz"
                }));
            }
        });
    });
</script>

TravelApp.Web/Areas/Admin/Views/Attraction/Edit.cshtml
@model TravelApp.Contracts.DTO.AttractionDto
    @{
        ViewBag.Title = "Edit";
    }

    <h2>Edit</h2>
@using (Html.BeginForm("Create", "Attraction", FormMethod.Post, new { enctype = "multipart/form-data", id = "frmID" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <div>
        Nazwa atrakcji
    </div>
    <p>
        @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
    </p>
    <p>
        Krótki Opis
    </p>
    <p>

        @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
    </p>
    <p>
        Długi Opis
    </p>
    <p>

        @Html.TextAreaFor(model => model.LongDescription, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.LongDescription, "", new { @class = "text-danger" })
    </p>
    <p>
        Adres
    </p>
    <p>

        @Html.TextBoxFor(model => model.Adress, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Adress, "", new { @class = "text-danger" })
    </p>
    <p>
        Średni czas zwiedzania
    </p>
    <p>

        @Html.TextBoxFor(model => model.AvrHoursTime, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.AvrHoursTime, "", new { @class = "text-danger" })
    </p>
    <p>
        Zdjęcie
    </p>
    <p>
        @Html.HiddenFor(i => i.FilesToBeUploaded)
        <div class="labelstyle">
            <label>Pliki</label>
        </div>

        <div id="uploaders">
            <input type="file" id="fileToUpload" name="fileUpload" multiple="multiple" style="float: left;" />
            <br />
            <span id="spnFile" style="float: left; color: #FF0000"></span>
            @Html.ValidationMessage("File")
            @Html.Hidden("hdnFileUpload")
        </div>
        <br />
        <div class="col-lg-6">
        </div>
        <br />
        <div class="control-section" style="padding: 0px;">
            <div id="selectedFiles"></div>
        </div>
    </p>
    <p>
        Kraj
    </p>
    <p>
        @Html.DropDownList("countryName", null, "Wybierz", new { @id = "Country", @class = "form-control" })
    </p>
    <p>
        Miasto
    </p>
    <p>

        @Html.DropDownList("cityName", null, "Wybierz", new { @id = "City", @class = "form-control" })
    </p>
        <p>
        </p>
        <input type="submit" value="Save" onclick="createAttraction.Check" class="form-control" />
}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script type="text/javascript">
    var createAttraction = {
        init: function () {
            var citiesSelect = $('#City');
            citiesSelect.empty();
            citiesSelect.append($('<option/>', {
                value: "0",
                text: "Wybierz"
            }));
        }
    }
    $(document).ready(function () {
        createAttraction.init();
        $('#Country').change(function () {
            var selectedCountry = $(this).val();

            if (selectedCountry != null && selectedCountry != '') {
                $.getJSON('@Url.Action("GetCitiesByCountryId")', { id: selectedCountry }, function (cities) {
                    var citiesSelect = $('#City');
                    citiesSelect.empty();
                    citiesSelect.append($('<option/>', {
                        value: "0",
                        text: "Wybierz"
                    }));
                    $.each(cities, function (index, city) {
                        citiesSelect.append($('<option/>', {
                            value: city.Id,
                            text: city.Name
                        }));
                    });
                });
            }
            else {
                var citiesSelect = $('#City');
                citiesSelect.empty();
                citiesSelect.append($('<option/>', {
                    value: "0",
                    text: "Wybierz"
                }));
            }
        });

  
    });
</script>

TravelApp.Web/Areas/Admin/Views/Attraction/Index.cshtml
@model IEnumerable<TravelApp.Contracts.DTO.AttractionDto>

@{
    ViewBag.Title = "Strona głowna panelu atrakcji";
}
<div class="spacing"></div>
<h2>Panel Atrakcji</h2>

<p>
    @Html.ActionLink("Utwórz nową atrakcję", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            Potwierdzenie zgodności 
        </th>
        <th>
            Miasto
        </th>
        <th>
            Kraj
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Description)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsActive, new { id = item.Id })
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.City.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Country.Name)
        </td>
        <td>
            @Html.ActionLink("Wyświetlaj/Nie Wyświetlaj", "SetVisibleAttraction", new { id = item.Id })
            @Html.ActionLink("Edytuj", "Edit", new {  id=item.Id  })
            @Html.ActionLink("Usuń", "Delete", new {  id=item.Id  })
        </td>
    </tr>
}

</table>

<script>
    $.get("ajax/test.html", function (data) {
        $(".result").html(data);
        alert("Load was performed.");
    });
</script>